In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
array35 = np.arange(1,10)

In [3]:
print(array35 + 10)

[11 12 13 14 15 16 17 18 19]


In [4]:
print(array35)

[1 2 3 4 5 6 7 8 9]


In [5]:
print(array35 * 10)

[10 20 30 40 50 60 70 80 90]


In [6]:
print(array35 / 10)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [7]:
print(array35 - 1)

[0 1 2 3 4 5 6 7 8]


In [8]:
array36 = np.arange(1,10)
print(array35+array36)

[ 2  4  6  8 10 12 14 16 18]


In [9]:
print(array35 ** array36)

[        1         4        27       256      3125     46656    823543
  16777216 387420489]


In [10]:
print(np.sqrt(array35))
print(np.log2(array35))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [11]:
array37 = np.array([[4, 5, 6], [7, 8, 9]])
array38 = np.array([[1, 2, 3], [3, 2, 1]])
print(array37 ** array38)
print(np.power(array37, array38))

[[  4  25 216]
 [343  64   9]]
[[  4  25 216]
 [343  64   9]]


In [12]:
array39 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array40 = np.array([1, 2, 3])
array39 + array40

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [13]:
m4 = np.array([[1, 3, 5], [2, 4, 6], [4, 7, 9]])
np.linalg.det(m4)

2.0000000000000013

In [14]:
# 解线性方程组ax=b
# 3*x1 + x2= 9，x1 + 2*x2 = 8
a = np.array([[3,1], [1,2]])
b = np.array([9, 8])
np.linalg.solve(a, b)

array([2., 3.])

In [3]:
array37 = np.array([1,2,3,4])
print(array37 + 10)
print(array37 - 5)
print(array37 * 10)


[11 12 13 14]
[-4 -3 -2 -1]
[10 20 30 40]


In [4]:
array38 = np.arange(1,10)

In [5]:
print(array38)

[1 2 3 4 5 6 7 8 9]


In [6]:
array39 = np.arange(1,10,2)

In [7]:
print(array39)

[1 3 5 7 9]


In [11]:
array40 = np.abs([1,2,3,-4])
print(array40)

[1 2 3 4]


In [12]:
array41 = np.arange(0,1,1) 

In [13]:
array42 = np.eye(3,4)
print(array42)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [15]:
array43 = np.append([1,2,3,4],[])

print(array43)

[1. 2. 3. 4.]


In [16]:
array44 = np.angle([12,21])
print(array44)

[0. 0.]


In [17]:
array37 = np.array([[4, 5, 6], [7, 8, 9]])
array38 = np.array([[1, 2, 3], [3, 2, 1]])
print(array37 ** array38)
print(np.power(array37, array38))

[[  4  25 216]
 [343  64   9]]
[[  4  25 216]
 [343  64   9]]


In [18]:
m4 = np.array([[1, 3, 5], [2, 4, 6], [4, 7, 9]])
np.linalg.det(m4)

2.0000000000000013

In [19]:
# 解线性方程组ax=b
# 3*x1 + x2= 9，x1 + 2*x2 = 8
a = np.array([[3,1], [1,2]])
b = np.array([9, 8])
np.linalg.solve(a, b)

array([2., 3.])

In [2]:
array1= np.add([1,2],[2,4])
print(array1)

[3 6]


In [4]:
array2 = np.subtract([1,2,3],[1,2,3])
print(array2)

[0 0 0]


In [5]:
array1 = np.multiply([1,2,3],[1,2,3])

In [7]:
print(array1)

[1 4 9]


In [3]:
a = [[1,2,3]]
b = [[2,3,6]]

In [10]:
array1 = np.multiply(a, b)
print(array1)

[[ 2  6 18]]


In [11]:
array1 = np.divide(a,b)
print(array1)

[[0.5        0.66666667 0.5       ]]


In [12]:
array1 = np.floor_divide(a,b)
print(array1)

[[0 0 0]]


In [13]:
array1 = np.mod(a,b)
print(array1)

[[1 2 3]]


In [15]:
array1 = np.allclose(a,b)
print(array1)

False


In [16]:
array1 = np.power(a,b)
print(array1)

[[  1   8 729]]


In [19]:
array1 = np.maximum(a,b)
print(array1)

[[2 3 6]]


In [20]:
array1 = np.fmax(a,b)
print(array1)

[[2 3 6]]


In [22]:
array1 = np.minimum(a,b)
print(array1)

[[1 2 3]]


In [4]:
array1 = np.dot(a,b)
print(array1)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [5]:
array39 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array40 = np.array([1, 2, 3])
array39 + array40

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [6]:
array41 = np.array([[1], [2], [3], [4]])
array39 + array41

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [7]:
array42 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array43 = np.array([[4, 4, 4], [5, 5, 5], [6, 6, 6]])
np.hstack((array42, array43))

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])