In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
array35 = np.arange(1,10)

In [3]:
print(array35 + 10)

[11 12 13 14 15 16 17 18 19]


In [4]:
print(array35)

[1 2 3 4 5 6 7 8 9]


In [5]:
print(array35 * 10)

[10 20 30 40 50 60 70 80 90]


In [6]:
print(array35 / 10)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [7]:
print(array35 - 1)

[0 1 2 3 4 5 6 7 8]


In [8]:
array36 = np.arange(1,10)
print(array35+array36)

[ 2  4  6  8 10 12 14 16 18]


In [9]:
print(array35 ** array36)

[        1         4        27       256      3125     46656    823543
  16777216 387420489]


In [10]:
print(np.sqrt(array35))
print(np.log2(array35))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [11]:
array37 = np.array([[4, 5, 6], [7, 8, 9]])
array38 = np.array([[1, 2, 3], [3, 2, 1]])
print(array37 ** array38)
print(np.power(array37, array38))

[[  4  25 216]
 [343  64   9]]
[[  4  25 216]
 [343  64   9]]


In [12]:
array39 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array40 = np.array([1, 2, 3])
array39 + array40

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [13]:
m4 = np.array([[1, 3, 5], [2, 4, 6], [4, 7, 9]])
np.linalg.det(m4)

2.0000000000000013

In [14]:
# 解线性方程组ax=b
# 3*x1 + x2= 9，x1 + 2*x2 = 8
a = np.array([[3,1], [1,2]])
b = np.array([9, 8])
np.linalg.solve(a, b)

array([2., 3.])

In [3]:
array37 = np.array([1,2,3,4])
print(array37 + 10)
print(array37 - 5)
print(array37 * 10)


[11 12 13 14]
[-4 -3 -2 -1]
[10 20 30 40]


In [4]:
array38 = np.arange(1,10)

In [5]:
print(array38)

[1 2 3 4 5 6 7 8 9]


In [6]:
array39 = np.arange(1,10,2)

In [7]:
print(array39)

[1 3 5 7 9]


In [11]:
array40 = np.abs([1,2,3,-4])
print(array40)

[1 2 3 4]


In [12]:
array41 = np.arange(0,1,1) 

In [13]:
array42 = np.eye(3,4)
print(array42)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [15]:
array43 = np.append([1,2,3,4],[])

print(array43)

[1. 2. 3. 4.]


In [16]:
array44 = np.angle([12,21])
print(array44)

[0. 0.]


In [17]:
array37 = np.array([[4, 5, 6], [7, 8, 9]])
array38 = np.array([[1, 2, 3], [3, 2, 1]])
print(array37 ** array38)
print(np.power(array37, array38))

[[  4  25 216]
 [343  64   9]]
[[  4  25 216]
 [343  64   9]]


In [18]:
m4 = np.array([[1, 3, 5], [2, 4, 6], [4, 7, 9]])
np.linalg.det(m4)

2.0000000000000013

In [19]:
# 解线性方程组ax=b
# 3*x1 + x2= 9，x1 + 2*x2 = 8
a = np.array([[3,1], [1,2]])
b = np.array([9, 8])
np.linalg.solve(a, b)

array([2., 3.])

In [2]:
array1= np.add([1,2],[2,4])
print(array1)

[3 6]


In [4]:
array2 = np.subtract([1,2,3],[1,2,3])
print(array2)

[0 0 0]


In [5]:
array1 = np.multiply([1,2,3],[1,2,3])

In [7]:
print(array1)

[1 4 9]


In [3]:
a = [[1,2,3]]
b = [[2,3,6]]

In [10]:
array1 = np.multiply(a, b)
print(array1)

[[ 2  6 18]]


In [11]:
array1 = np.divide(a,b)
print(array1)

[[0.5        0.66666667 0.5       ]]


In [12]:
array1 = np.floor_divide(a,b)
print(array1)

[[0 0 0]]


In [13]:
array1 = np.mod(a,b)
print(array1)

[[1 2 3]]


In [15]:
array1 = np.allclose(a,b)
print(array1)

False


In [16]:
array1 = np.power(a,b)
print(array1)

[[  1   8 729]]


In [19]:
array1 = np.maximum(a,b)
print(array1)

[[2 3 6]]


In [20]:
array1 = np.fmax(a,b)
print(array1)

[[2 3 6]]


In [22]:
array1 = np.minimum(a,b)
print(array1)

[[1 2 3]]


In [4]:
array1 = np.dot(a,b)
print(array1)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [5]:
array39 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array40 = np.array([1, 2, 3])
array39 + array40

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [6]:
array41 = np.array([[1], [2], [3], [4]])
array39 + array41

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [7]:
array42 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array43 = np.array([[4, 4, 4], [5, 5, 5], [6, 6, 6]])
np.hstack((array42, array43))

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])

In [3]:
fuzzyMap = {
  'zh': ['z'],
  'z': ['zh'],
  'ch': ['c'],
  'c': ['ch'],
  'sh': ['s'],
  's': ['sh'],
  'n': ['l'],
  'l': ['n','r'],
  'r': ['l'],
  'f': ['h','hu'],
  'h': ['f'],
  'hu': ['f'],
  'wang': ['huang'],
  'huang': ['wang'],
  'ang': ['an'],
  'an': ['ang'],
  'eng': ['en'],
  'en': ['eng'],
  'ing': ['in'],
  'in': ['ing']
}

strMap = {
  'z': ['z', 'h'],
  'c': ['c', 'h'],
  's': ['s', 'h'],
  'n': ['n'],
  'l': ['l'],
  'r': ['r'],
  'f': ['f'],
  'h': ['h', 'u'],
  'wang': ['wang'],
  'huang': ['huang'],
  'an': ['an','g'],
  'en': ['en', 'g'],
  'in': ['in','g'],
}

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def add_node(self, data):
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_node

    def display(self):
        current = self.head
        while current:
            print(current.data)
            current = current.next
print(fuzzyMap)

{'zh': ['z'], 'z': ['zh'], 'ch': ['c'], 'c': ['ch'], 'sh': ['s'], 's': ['sh'], 'n': ['l'], 'l': ['n', 'r'], 'r': ['l'], 'f': ['h', 'hu'], 'h': ['f'], 'hu': ['f'], 'wang': ['huang'], 'huang': ['wang'], 'ang': ['an'], 'an': ['ang'], 'eng': ['en'], 'en': ['eng'], 'ing': ['in'], 'in': ['ing']}


In [6]:
my_list = LinkedList()

# 添加节点
my_list.add_node(1).add_node(2).add_node(3)

# 显示链表内容
my_list.display()
  
    

AttributeError: 'NoneType' object has no attribute 'add_node'

In [ ]:
def mappinyin(string):
  str_len = len(string)
  index = 0 
  while index < str_len:
    if strMap(string[index]) is None:
      index++
      continue
    if len(strMap(string[index])) == 1:
      string.replace 
    
  for char in str:
    
      

In [4]:
array1 = np.arange(1,10)
print(array1+10)



[11 12 13 14 15 16 17 18 19]


In [5]:
array2 = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
print(array2)


[1 1 1 2 2 2 3 3 3]


In [6]:
print(np.sqrt(array1))
print(np.log2(array2))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.        0.        0.        1.        1.        1.        1.5849625
 1.5849625 1.5849625]


In [7]:
print(np.abs(array1))

[1 2 3 4 5 6 7 8 9]


In [8]:
print(np.fabs(array1))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:
print(np.sqrt(array1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [10]:
np.square(array1)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
np.exp(array1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [12]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
np.log10(array2)

array([0.        , 0.        , 0.        , 0.30103   , 0.30103   ,
       0.30103   , 0.47712125, 0.47712125, 0.47712125])

In [14]:
np.sign(array1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ceil(array1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.floor(array1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
array3 = [0.1,0.6]

In [18]:
np.ceil(array3)

array([1., 1.])

In [19]:
np.floor(array3)

array([0., 0.])

In [20]:
np.isnan(array1)

array([False, False, False, False, False, False, False, False, False])

In [21]:
array4 = [NaN]

NameError: name 'NaN' is not defined

In [22]:
np.isfinite(array1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [23]:
np.cos(array1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [24]:
np.cosh(array1)

array([1.54308063e+00, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01, 2.01715636e+02, 5.48317035e+02, 1.49047916e+03,
       4.05154203e+03])

In [25]:
np.rint(array1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.rint(array3)

array([0., 1.])

In [27]:
np.unique(array1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array5 = [1,2,3,4,5,6,6,6,6]


In [29]:
np.unique(array5)

array([1, 2, 3, 4, 5, 6])

In [30]:
np.copy(array1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.append(array1,2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2])

In [32]:
np.insert(array1,1)

TypeError: insert() missing 1 required positional argument: 'values'

In [33]:
np.insert(array1,1,1111)

array([   1, 1111,    2,    3,    4,    5,    6,    7,    8,    9])

In [34]:
np.argwhere(array1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int64)